name: Build

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false

      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Clone code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install npm
        run: npm install

      # Linuxの場合はWebviewがないのでWebview関係をインストールする
      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y \
            libglib2.0-dev \
            libgtk-3-dev \
            libwebkit2gtk-4.1-dev \
            libappindicator3-dev \
            librsvg2-dev \
            pkg-config

      - uses: tauri-apps/tauri-action@v0
        with:
          tagName: v__VERSION__
          releaseName: 'Widget v__VERSION__'
          releaseBody: |
            ## Widget v__VERSION__をリリースしました!
            - インストール方法は以下です

            ## Windows
            - 拡張子がmsiのインストーラーをダウンロードし、実行してください

            ## Mac
            - 拡張子がdmgのファイルを実行し、アプリフォルダにドラッグ&ドロップしてください

            ## Linux
            - 単体で動かす場合は拡張子がAppImageのファイルを実行してください
            - Ubuntu/Debian系でインストールする場合は拡張子がdebのファイルをインストールしてください
            - Fedora/RedHat系でインストールする場合は拡張子がrpmのファイルをインストールしてください
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
